# Generated by Django 3.2.5 on 2021-08-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todproof', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='document',
            new_name='message',
        ),
    ]
