# Generated by Django 3.2.5 on 2021-08-05 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
        ('todproof', '0002_auto_20210805_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Assignment',
        ),
        migrations.RenameField(
            model_name='addition',
            old_name='task',
            new_name='assignment',
        ),
    ]
