# Generated by Django 3.2.5 on 2021-08-11 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todproof', '0005_auto_20210805_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='context',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(10)], verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='todproof.sentence'),
        ),
    ]
