# Generated by Django 3.2.5 on 2021-08-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cur_task',
            new_name='cur_assign',
        ),
    ]
